version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/slidev/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ci:
        patterns:
          - "*"
