version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/slidev/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
    groups:
      ci:
        patterns:
          - "*"
