🍱asset:
- changed-files:
  - any-glob-to-any-file: 'static/**'
♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
📝documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
🚀enhancement:
 - head-branch: ['^feature', 'feature', '^enhancement', 'enhancement']
🪸git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '.gitignore']
🎮game:
- changed-files:
  - any-glob-to-any-file: 'game/**'
🕶️glass:
- changed-files:
  - any-glob-to-any-file: 'glass/**'
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: '.editorconfig'
💡LED:
- changed-files:
  - any-glob-to-any-file: 'LED/**'
🎼music:
- changed-files:
  - any-glob-to-any-file: 'music/**'
🤖robot:
- changed-files:
  - any-glob-to-any-file: 'robot/**'
📽️slidev:
- changed-files:
  - any-glob-to-any-file: 'slidev/**'
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
